<script lang="ts">
// Generated by scripts/registry-refresh.mjs. Do not edit by hand.
import { onMount, setContext, type Snippet } from "svelte";
import { type BambiBehavior, getAttr, setAttr, getBoolAttr } from "../bambi-helpers";

const TABS_ROOT = "data-bambi-tabs" as const;
const TABS_LIST = "data-bambi-tabs-list" as const;
const TABS_TRIGGER = "data-bambi-tabs-trigger" as const;
const TABS_CONTENT = "data-bambi-tabs-content" as const;
const TABS_VALUE = "data-value" as const;
const TABS_DEFAULT_VALUE = "data-default-value" as const;
const TABS_CONTROLLED = "data-controlled" as const;
const TABS_ORIENTATION = "data-orientation" as const;
const TABS_ACTIVATION_MODE = "data-activation-mode" as const;
const TABS_DISABLED = "data-disabled" as const;
const TABS_STATE = "data-state" as const;
const TABS_EVENT_VALUE_CHANGE = "bambi:value-change" as const;

export type TabsOrientation = "horizontal" | "vertical";
export type TabsActivationMode = "automatic" | "manual";

export interface TabsValueChangeDetail {
  value: string;
  previousValue: string | null;
  source: "click" | "keyboard";
}


interface RovingFocusOptions {
  
  orientation?: "horizontal" | "vertical" | "both";
  
  loop?: boolean;
  
  getItems: () => Element[];
  
  isDisabled?: (item: Element) => boolean;
  
  onFocus: (item: Element) => void;
  
  onActivate?: (item: Element) => void;
}

interface RovingFocus {
  destroy(): void;
}


function createRovingFocus(
  container: Element,
  options: RovingFocusOptions,
): RovingFocus {
  const abort = new AbortController();
  const { signal } = abort;
  const loop = options.loop ?? true;
  const orientation = options.orientation ?? "horizontal";

  const isHorizontal = orientation === "horizontal" || orientation === "both";
  const isVertical = orientation === "vertical" || orientation === "both";

  container.addEventListener(
    "keydown",
    (event: Event) => {
      const e = event as KeyboardEvent;
      const items = options
        .getItems()
        .filter((item) => !(options.isDisabled?.(item) ?? false));

      if (items.length === 0) return;

      const focused = items.findIndex((item) => item === document.activeElement);
      if (focused === -1) return;

      let next: Element | undefined;

      if (
        (isHorizontal && e.key === "ArrowRight") ||
        (isVertical && e.key === "ArrowDown")
      ) {
        e.preventDefault();
        const nextIndex = loop
          ? (focused + 1) % items.length
          : Math.min(focused + 1, items.length - 1);
        next = items[nextIndex];
      } else if (
        (isHorizontal && e.key === "ArrowLeft") ||
        (isVertical && e.key === "ArrowUp")
      ) {
        e.preventDefault();
        const prevIndex = loop
          ? (focused - 1 + items.length) % items.length
          : Math.max(focused - 1, 0);
        next = items[prevIndex];
      } else if (e.key === "Home") {
        e.preventDefault();
        next = items[0];
      } else if (e.key === "End") {
        e.preventDefault();
        next = items[items.length - 1];
      } else if ((e.key === "Enter" || e.key === " ") && options.onActivate) {
        e.preventDefault();
        const item = items[focused];
        if (item) options.onActivate(item);
        return;
      }

      if (next) options.onFocus(next);
    },
    { signal },
  );

  return {
    destroy() {
      abort.abort();
    },
  };
}


export interface TabsOptions {
  value?: string;
  defaultValue?: string;
  controlled?: boolean;
  orientation?: TabsOrientation;
  activationMode?: TabsActivationMode;
  disabled?: boolean;
}

function dispatchTabsEvent(element: Element, detail: TabsValueChangeDetail): void {
  element.dispatchEvent(
    new CustomEvent<TabsValueChangeDetail>(TABS_EVENT_VALUE_CHANGE, {
      bubbles: true,
      cancelable: false,
      composed: false,
      detail,
    }),
  );
}

class TabsBehavior implements BambiBehavior {
  private static _idCounter = 0;

  private readonly root: Element;
  private options: TabsOptions;
  private currentValue: string | null = null;
  private readonly _id: string;
  private readonly destroyAbort: AbortController;
  private bindAbort: AbortController;
  private rovingFocus: RovingFocus | null = null;

  constructor(root: Element, options: TabsOptions = {}) {
    this.root = root;
    this.options = options;
    this._id = root.id || `bambi-tabs-${++TabsBehavior._idCounter}`;
    this.destroyAbort = new AbortController();
    this.bindAbort = new AbortController();
  }

  sync(): void {
    this.bindAbort.abort();
    this.rovingFocus?.destroy();
    this.bindAbort = new AbortController();

    const orientation = (
      this.options.orientation ??
      getAttr(this.root, TABS_ORIENTATION, "horizontal")
    ) as TabsOrientation;

    setAttr(this.root, TABS_ORIENTATION, orientation);
    setAttr(
      this.root,
      TABS_ACTIVATION_MODE,
      this.options.activationMode ?? getAttr(this.root, TABS_ACTIVATION_MODE, "automatic"),
    );
    if (this.options.disabled !== undefined) {
      setAttr(this.root, TABS_DISABLED, this.options.disabled ? "true" : null);
    }
    for (const list of Array.from(this.root.querySelectorAll(`[${TABS_LIST}]`))) {
      list.setAttribute("role", "tablist");
      list.setAttribute("aria-orientation", orientation);
    }

    const value =
      (this.options.value ?? getAttr(this.root, TABS_VALUE, "")) ||
      (this.options.defaultValue ?? getAttr(this.root, TABS_DEFAULT_VALUE, "")) ||
      this.firstTriggerValue();
    if (value) this.applyState(value);

    this.bindEvents();
  }

  update(options: TabsOptions = {}): void {
    const prev = this.options;
    this.options = { ...this.options, ...options };

    const orientation = (
      this.options.orientation ??
      getAttr(this.root, TABS_ORIENTATION, "horizontal")
    ) as TabsOrientation;
    setAttr(this.root, TABS_ORIENTATION, orientation);
    setAttr(this.root, TABS_ACTIVATION_MODE, this.activationMode());
    if (this.options.disabled !== undefined) {
      setAttr(this.root, TABS_DISABLED, this.options.disabled ? "true" : null);
    }
    for (const list of Array.from(this.root.querySelectorAll(`[${TABS_LIST}]`))) {
      list.setAttribute("role", "tablist");
      list.setAttribute("aria-orientation", orientation);
    }

    if (options.orientation !== undefined && options.orientation !== prev.orientation) {
      this.rovingFocus?.destroy();
      this.rovingFocus = this.createRovingFocusInstance(orientation);
    }

    if (options.value !== undefined && options.value !== prev.value && options.value) {
      this.applyState(options.value);
    } else if (this.currentValue) {
      this.applyState(this.currentValue);
    }
  }

  destroy(): void {
    this.destroyAbort.abort();
    this.bindAbort.abort();
    this.rovingFocus?.destroy();
  }

  private firstTriggerValue(): string | null {
    return this.root.querySelector(`[${TABS_TRIGGER}]`)?.getAttribute(TABS_VALUE) ?? null;
  }

  private triggers(): Element[] {
    return Array.from(this.root.querySelectorAll(`[${TABS_TRIGGER}]`));
  }

  private contents(): Element[] {
    return Array.from(this.root.querySelectorAll(`[${TABS_CONTENT}]`));
  }

  
  private applyState(newValue: string): void {
    const isControlled =
      this.options.controlled ?? getBoolAttr(this.root, TABS_CONTROLLED);

    if (!isControlled) setAttr(this.root, TABS_VALUE, newValue);
    this.currentValue = newValue;

    for (const trigger of this.triggers()) {
      const val = trigger.getAttribute(TABS_VALUE) ?? "";
      if (!trigger.id) trigger.id = `${this._id}-trigger-${val}`;
      trigger.setAttribute("role", "tab");
      trigger.setAttribute("aria-controls", `${this._id}-content-${val}`);

      const isActive = val === newValue;
      setAttr(trigger, TABS_STATE, isActive ? "active" : "inactive");
      trigger.setAttribute("aria-selected", String(isActive));
      trigger.setAttribute("tabindex", isActive ? "0" : "-1");
      if (getBoolAttr(trigger, TABS_DISABLED)) {
        trigger.setAttribute("aria-disabled", "true");
      } else {
        trigger.removeAttribute("aria-disabled");
      }
    }

    for (const content of this.contents()) {
      const val = content.getAttribute(TABS_VALUE) ?? "";
      if (!content.id) content.id = `${this._id}-content-${val}`;
      content.setAttribute("role", "tabpanel");
      content.setAttribute("aria-labelledby", `${this._id}-trigger-${val}`);
      if (!content.hasAttribute("tabindex")) content.setAttribute("tabindex", "0");

      const isActive = val === newValue;
      setAttr(content, TABS_STATE, isActive ? "active" : "inactive");
      if (isActive) {
        content.removeAttribute("hidden");
      } else {
        content.setAttribute("hidden", "");
      }
    }
  }

  
  private applyValue(newValue: string, source: "click" | "keyboard"): void {
    if (newValue === this.currentValue) return;

    const isControlled =
      this.options.controlled ?? getBoolAttr(this.root, TABS_CONTROLLED);
    const previousValue = this.currentValue;

    if (!isControlled) this.applyState(newValue);

    dispatchTabsEvent(this.root, { value: newValue, previousValue, source });
  }

  private activationMode(): TabsActivationMode {
    return (
      this.options.activationMode ??
      getAttr(this.root, TABS_ACTIVATION_MODE, "automatic")
    ) as TabsActivationMode;
  }

  private focusTrigger(trigger: Element): void {
    if (trigger instanceof HTMLElement) trigger.focus();
  }

  private activateFocusedTrigger(trigger: Element): void {
    const value = trigger.getAttribute(TABS_VALUE);
    if (value) this.applyValue(value, "keyboard");
  }

  private createRovingFocusInstance(orientation: TabsOrientation): RovingFocus {
    return createRovingFocus(this.root, {
      orientation,
      getItems: () => {
        if (this.options.disabled ?? getBoolAttr(this.root, TABS_DISABLED)) return [];
        return this.triggers();
      },
      isDisabled: (el) =>
        getBoolAttr(el, TABS_DISABLED) || el.getAttribute("aria-disabled") === "true",
      onFocus: (el) => {
        this.focusTrigger(el);
        if (this.activationMode() === "automatic") this.activateFocusedTrigger(el);
      },
      onActivate: (el) => this.activateFocusedTrigger(el),
    });
  }

  private bindEvents(): void {
    const { signal } = this.bindAbort;

    this.root.addEventListener(
      "click",
      (event: Event) => {
        const disabled = this.options.disabled ?? getBoolAttr(this.root, TABS_DISABLED);
        if (disabled) return;

        const target = (event.target as Element).closest(`[${TABS_TRIGGER}]`);
        if (!target || !this.root.contains(target)) return;

        const isDisabledTrigger =
          getBoolAttr(target, TABS_DISABLED) ||
          target.getAttribute("aria-disabled") === "true";
        if (isDisabledTrigger) return;

        const value = target.getAttribute(TABS_VALUE);
        if (!value) return;

        this.applyValue(value, "click");
      },
      { signal },
    );

    const orientation = (
      this.options.orientation ?? getAttr(this.root, TABS_ORIENTATION, "horizontal")
    ) as TabsOrientation;
    this.rovingFocus = this.createRovingFocusInstance(orientation);
  }
}

interface Props extends Omit<TabsOptions, "controlled"> {
  children?: Snippet;
  class?: string;
  [key: string]: unknown;
  onValueChange?: (detail: TabsValueChangeDetail) => void;
}

let {
  value,
  defaultValue,
  orientation = "horizontal",
  activationMode = "automatic",
  disabled,
  onValueChange,
  children,
  ...props
}: Props = $props();

const controlled = $derived(value !== undefined);
setContext("bambi-tabs-value", () => value ?? defaultValue);

  $effect(() => {
    if (value !== undefined && defaultValue !== undefined) {
      console.warn(
        "[bambiui/tabs] Tabs received both `value` and `defaultValue`. Use `value` for controlled mode or `defaultValue` for uncontrolled mode, not both.",
      );
    }
  });

let rootEl: HTMLElement | undefined = $state();
let behavior: TabsBehavior | undefined;

onMount(() => {
  const onValueChangeHandler = (event: Event) => {
    const e = event as CustomEvent<TabsValueChangeDetail>;
    onValueChange?.(e.detail);
  };
  rootEl!.addEventListener(TABS_EVENT_VALUE_CHANGE, onValueChangeHandler);
  behavior = new TabsBehavior(rootEl!, {
      value,
      defaultValue,
      orientation,
      activationMode,
      disabled,
      controlled,
  });
  behavior.sync();
  return () => {
    rootEl!.removeEventListener(TABS_EVENT_VALUE_CHANGE, onValueChangeHandler);
    behavior?.destroy();
  };
});

// Svelte 5 (runes): prop changes drive controller re-sync via this $effect.
// Dynamic children (conditional child parts from parent state) cannot be
// tracked here — Svelte 5 Snippets do not expose a reactive identity that
// $effect can subscribe to without calling the Snippet. If the child structure
// changes at runtime, wrap <Tabs> in a {#key} block keyed
// to the structure.
$effect(() => {
  behavior?.update?.({
      value,
      defaultValue,
      orientation,
      activationMode,
      disabled,
      controlled,
  });
});
</script>
<div
  bind:this={rootEl}
  {...props}
  data-bambi-tabs=""
  data-value={value}
  data-default-value={defaultValue}
  data-orientation={orientation}
  data-activation-mode={activationMode}
  data-disabled={disabled ? "true" : undefined}
  data-controlled={controlled ? "true" : undefined}
>
  {@render children?.()}
</div>
