<script lang="ts">
// Generated by scripts/registry-refresh.mjs. Do not edit by hand.
import { onMount, type Snippet } from "svelte";
import { type BambiBehavior, getAttr, setAttr, getBoolAttr } from "../bambi-helpers";

const BUTTON_ROOT = "data-bambi-button" as const;
const BUTTON_VARIANT = "data-variant" as const;
const BUTTON_SIZE = "data-size" as const;
const BUTTON_DISABLED = "data-disabled" as const;
const BUTTON_LOADING = "data-loading" as const;

export type ButtonVariant =
  | "primary"
  | "secondary"
  | "outline"
  | "ghost"
  | "danger"
  | "success"
  | "warning";
export type ButtonSize = "sm" | "md" | "lg" | "icon";


export interface ButtonOptions {
  as?: string;
  variant?: ButtonVariant;
  size?: ButtonSize;
  disabled?: boolean;
  loading?: boolean;
}

class ButtonBehavior implements BambiBehavior {
  private readonly root: Element;
  private options: ButtonOptions;

  constructor(root: Element, options: ButtonOptions = {}) {
    this.root = root;
    this.options = options;
  }

  sync(): void {
    this.applyState();
  }

  update(options: ButtonOptions = {}): void {
    this.options = { ...this.options, ...options };
    this.applyState();
  }

  destroy(): void {}

  private applyState(): void {
    const variant = this.options.variant ?? getAttr(this.root, BUTTON_VARIANT, "primary");
    const size = this.options.size ?? getAttr(this.root, BUTTON_SIZE, "md");
    const disabled = this.options.disabled ?? getBoolAttr(this.root, BUTTON_DISABLED);
    const loading = this.options.loading ?? getBoolAttr(this.root, BUTTON_LOADING);
    const effectivelyDisabled = disabled || loading;
    const isNativeButton = this.root.tagName.toLowerCase() === "button";

    setAttr(this.root, BUTTON_VARIANT, variant);
    setAttr(this.root, BUTTON_SIZE, size);
    setAttr(this.root, BUTTON_DISABLED, effectivelyDisabled ? "true" : null);
    setAttr(this.root, BUTTON_LOADING, loading ? "true" : null);
    setAttr(this.root, "aria-busy", loading ? "true" : null);

    if (isNativeButton) {
      if (this.root instanceof HTMLButtonElement && !this.root.getAttribute("type")) {
        this.root.type = "button";
      }
      if (this.root instanceof HTMLButtonElement) {
        this.root.disabled = effectivelyDisabled;
      } else {
        setAttr(this.root, "disabled", effectivelyDisabled ? "" : null);
      }
      this.root.removeAttribute("aria-disabled");
    } else {
      setAttr(this.root, "disabled", null);
      setAttr(this.root, "aria-disabled", effectivelyDisabled ? "true" : null);
    }
  }
}

interface Props extends ButtonOptions {
  children?: Snippet;
  class?: string;
  [key: string]: unknown;
}

let {
  as,
  variant = "primary",
  size = "md",
  disabled,
  loading,
  children,
  ...props
}: Props = $props();

const Component = $derived(as ?? "button");
const isNativeElement = $derived(Component === "button");
const effectiveDisabled = $derived(Boolean(disabled || loading));
const nativeType = $derived(isNativeElement ? (typeof props.type === "string" ? props.type : "button") : undefined);
const polymorphicAttrs = $derived({
  type: nativeType,
  disabled: isNativeElement ? effectiveDisabled : undefined,
  "aria-disabled": !isNativeElement && effectiveDisabled ? true : undefined,
  "aria-busy": loading ? true : undefined,
});

let rootEl: HTMLElement | undefined = $state();
let behavior: ButtonBehavior | undefined;

onMount(() => {
  behavior = new ButtonBehavior(rootEl!, {
      as,
      variant,
      size,
      disabled,
      loading,
  });
  behavior.sync();
  return () => behavior?.destroy();
});

// Svelte 5 (runes): prop changes drive controller re-sync via this $effect.
// Dynamic children (conditional child parts from parent state) cannot be
// tracked here — Svelte 5 Snippets do not expose a reactive identity that
// $effect can subscribe to without calling the Snippet. If the child structure
// changes at runtime, wrap <Button> in a {#key} block keyed
// to the structure.
$effect(() => {
  behavior?.update?.({
      as,
      variant,
      size,
      disabled,
      loading,
  });
});
</script>
<svelte:element
  this={Component}
  bind:this={rootEl}
  {...props}
  {...polymorphicAttrs}
  data-bambi-button=""
  data-variant={variant}
  data-size={size}
  data-disabled={effectiveDisabled ? "true" : undefined}
  data-loading={loading ? "true" : undefined}
>
  {@render children?.()}
</svelte:element>
